// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// The ID of the product.
type Product struct {
	ProductID string   `json:"productId"`
	Name      *string  `json:"name,omitempty"`
	Price     *float64 `json:"price,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

// User is a federated entity, keyed by userId.
type User struct {
	UserID string  `json:"userId"`
	Name   *string `json:"name,omitempty"`
}

func (User) IsEntity() {}
