package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/fraser-isbester/federated-gql/services/graphql-gateway/graph/model"
)

// FindProductByProductID is the resolver for the findProductByProductID field.
func (r *entityResolver) FindProductByProductID(ctx context.Context, productID string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: FindProductByProductID - findProductByProductID"))
}

// FindUserByUserID is the resolver for the findUserByUserID field.
func (r *entityResolver) FindUserByUserID(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: FindUserByUserID - findUserByUserID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
